# Generated by Django 4.1 on 2022-08-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
