# Generated by Django 4.1 on 2022-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_alter_todo_project_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Created', 'created'), ('In progress', 'inprogress'), ('Cancelled', 'cancelled'), ('Done', 'done')], default='created', max_length=16),
        ),
    ]
