# Generated by Django 4.1 on 2022-08-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_users'),
        ('todos', '0006_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ManyToManyField(null=True, to='project.project'),
        ),
    ]
